version: '3.4'

services:
  auth_service:
    command: --seed
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:5000
  shop_service:
    command: --enable-migrations
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:5000
